# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll.xci
# IP: The module: 'pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll.xci
# IP: The module: 'pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/LRU Project/LRU Project.srcs/sources_1/ip/pll/pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
