# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mfp_nexys4_ddr.xdc

# XDC: imports/SD Code/Nexys-4-DDR-pins.xdc

# XDC: C:/Users/aam08331/Documents/GitHub/4280-Group12/LRU/LRU Project/VGA Code/Nexys4DDR_VGA.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
