# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mfp_nexys4_ddr.xdc

# XDC: imports/SD Code/Nexys-4-DDR-pins.xdc

# XDC: C:/Users/amr21/Downloads/FPGA_Projects_SaifAlomari-main/FPGA_Projects_SaifAlomari-main/SystemVerilog_FPGA_Projects/13- Vga Demo Square Generator/Constraints/Nexys4DDR_VGA.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
