# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mfp_nexys4_ddr.xdc

# XDC: C:/Users/Amr/Documents/GitHub/4280-Group12/LRU/DDR2 Example/mig_example-master/sdCode/Nexys-4-DDR-pins.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
